general:
  artifacts:
    - "~/outputs-colin"
    - "~/outputs-colin-labelmask"

machine:
  services:
    - docker #don't use 1.10 - caching is broken

dependencies:
  cache_directories:
    - "~/docker"
    - "~/data"

  override:
    - if [[ ! -d ~/data/ds003_downsampled ]]; then wget -c --no-check-certificate -O ${HOME}/ds003_downsampled_v2.tar "https://osf.io/8s29u/download" && mkdir -p ${HOME}/data && tar xf ${HOME}/ds003_downsampled_v2.tar -C ${HOME}/data; fi
    - if [[ -e ~/docker/image.tar ]]; then docker load -i ~/docker/image.tar; fi :
        timeout: 21600
    - git describe --tags > version
    - docker build -t bids/${CIRCLE_PROJECT_REPONAME,,} . :
        timeout: 21600
    - mkdir -p ~/docker; docker save "bids/${CIRCLE_PROJECT_REPONAME,,}" > ~/docker/image.tar :
        timeout: 21600
    - mkdir -p ${HOME}/outputs-colin
    - mkdir -p ${HOME}/outputs-colin-labelmask

test:
  override:
    # print version
    - docker run -ti --rm --read-only -v /tmp:/tmp -v /var/tmp:/var/tmp -v ${HOME}/data/ds003_downsampled:/bids_dataset bids/${CIRCLE_PROJECT_REPONAME,,} --version
    # template level run for downsampled dataset no masking
    - docker run -ti --rm --read-only -v /tmp:/tmp -v /var/tmp:/var/tmp -v ${HOME}/data/ds003_downsampled:/bids_dataset -v ${HOME}/outputs-colin:/outputs bids/${CIRCLE_PROJECT_REPONAME,,} --n_cpus 2 --segmentation_type colin27-subcortical /bids_dataset /outputs participant1 --participant_label 01 :
        timeout: 21600
    - docker run -ti --rm --read-only -v /tmp:/tmp -v /var/tmp:/var/tmp -v ${HOME}/data/ds003_downsampled:/bids_dataset -v ${HOME}/outputs-colin:/outputs bids/${CIRCLE_PROJECT_REPONAME,,} --n_cpus 2 --segmentation_type colin27-subcortical /bids_dataset /outputs participant1 --participant_label 02 :
        timeout: 2160
    # participant level tests for a longitudinal dataset no masking
    - docker run -ti --rm --read-only -v /tmp:/tmp -v /var/tmp:/var/tmp -v ${HOME}/data/ds003_downsampled:/bids_dataset -v ${HOME}/outputs-colin:/outputs bids/${CIRCLE_PROJECT_REPONAME,,} --n_cpus 2 --segmentation_type colin27-subcortical /bids_dataset /outputs participant2 --participant_label 01 :
        timeout: 21600
    - docker run -ti --rm --read-only -v /tmp:/tmp -v /var/tmp:/var/tmp -v ${HOME}/data/ds003_downsampled:/bids_dataset -v ${HOME}/outputs-colin:/outputs bids/${CIRCLE_PROJECT_REPONAME,,} --n_cpus 2 --segmentation_type colin27-subcortical /bids_dataset /outputs participant2 --participant_label 02 :
        timeout: 21600
    # template level run for downsampled dataset with masking
    - docker run -ti --rm --read-only -v /tmp:/tmp -v /var/tmp:/var/tmp -v ${HOME}/data/ds003_downsampled:/bids_dataset -v ${HOME}/outputs-colin-labelmask:/outputs bids/${CIRCLE_PROJECT_REPONAME,,} --n_cpus 2 --label-masking --segmentation_type colin27-subcortical /bids_dataset /outputs participant1 --participant_label 01 :
        timeout: 21600
    - docker run -ti --rm --read-only -v /tmp:/tmp -v /var/tmp:/var/tmp -v ${HOME}/data/ds003_downsampled:/bids_dataset -v ${HOME}/outputs-colin-labelmask:/outputs bids/${CIRCLE_PROJECT_REPONAME,,} --n_cpus 2 --label-masking --segmentation_type colin27-subcortical /bids_dataset /outputs participant1 --participant_label 02 :
        timeout: 2160
    # participant level tests for a longitudinal dataset with masking
    - docker run -ti --rm --read-only -v /tmp:/tmp -v /var/tmp:/var/tmp -v ${HOME}/data/ds003_downsampled:/bids_dataset -v ${HOME}/outputs-colin-labelmask:/outputs bids/${CIRCLE_PROJECT_REPONAME,,} --n_cpus 2 --label-masking --segmentation_type colin27-subcortical /bids_dataset /outputs participant2 --participant_label 01 :
        timeout: 21600
    - docker run -ti --rm --read-only -v /tmp:/tmp -v /var/tmp:/var/tmp -v ${HOME}/data/ds003_downsampled:/bids_dataset -v ${HOME}/outputs-colin-labelmask:/outputs bids/${CIRCLE_PROJECT_REPONAME,,} --n_cpus 2 --label-masking --segmentation_type colin27-subcortical /bids_dataset /outputs participant2 --participant_label 02 :
        timeout: 21600

deployment:
  hub:
    owner: BIDS-Apps
    tag: /.*/
    commands:
      - if [[ -n "$DOCKER_PASS" ]]; then docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS && docker push bids/${CIRCLE_PROJECT_REPONAME,,}:latest; fi :
          timeout: 21600
      - if [[ -n "$DOCKER_PASS" ]]; then docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS && docker tag bids/${CIRCLE_PROJECT_REPONAME,,} bids/${CIRCLE_PROJECT_REPONAME,,}:$CIRCLE_TAG && docker push bids/${CIRCLE_PROJECT_REPONAME,,}:$CIRCLE_TAG; fi :
          timeout: 21600
